blueprint:
  name: Price Alert and Entity Shutdown
  description: Sends a notification if the price tracking entity goes above a predefined value, then turns off specified entities and notifies which ones were turned off.
  domain: automation
  input:
    price_entity:
      name: Price Tracking Entity
      description: The entity that tracks the price.
      selector:
        entity:
          domain: sensor
    price_threshold:
      name: Price Threshold (cents)
      description: The price value in cents that triggers the alert and actions.
      default: 50
      selector:
        number:
          min: 0
          max: 300
    ttl:
      name: Time to Live (seconds)
      description: The time for messages to sit in notification center before expiring, in seconds.
      default: 60
      selector:
        number:
          min: 0
          max: 86400
    notify_device:
      name: Mobile Device
      description: Select a device that runs the official Home Assistant app to receive notifications. If you wish to notify a group of devices, use the field below to override this selection. This can be left blank in that case
      default: ""
      selector:
        device:
          integration: mobile_app
    notify_group:
      name: Notification Group
      description: |
        The name of the group to send notifications to.
        If set, this will override individual devices above.
      default: ""
    monitored_entities:
      name: Monitored Entities
      description: List of entities to monitor and turn off if the price exceeds the threshold.
      selector:
        device: 
          integration: mobile_app

variables:
  price_entity: !input price_entity
  price_threshold: !input price_threshold
  notify_device: !input notify_device
  group: !input notify_group
  group_target: "{{ group | lower | replace('notify.', '') | replace(' ','_') }}"
  monitored_entities: !input monitored_entities
  ttl: !input ttl

trigger:
  - platform: numeric_state
    entity_id: !input price_entity
    value_template: "{{ state | float(default=1.0) | multiply(100) }}"
    above: !input price_threshold

condition: []

action:
  - variables:
      switched_on_entities: >
        {{ expand(monitored_entities) | selectattr('state', 'ne', 'off') | map(attribute='entity_id') | list }}
      switched_on_entities_names: >
        {{ expand(monitored_entities) | selectattr('state', 'ne', 'off') | map(attribute='attributes.friendly_name') | list }}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ switched_on_entities | length > 0 }}"
        sequence:
          - choose:
            - conditions: "{{ not group_target }}"
              sequence:
                - device_id: !input notify_device
                  domain: mobile_app
                  type: notify
                  title: "Amber Price Alert Notification"
                  message: >
                    The price of ${{ states(price_entity) }} has exceeded {{ '$%.2f'| format(price_threshold | float | multiply(0.01)) }}. Turning off the following entities: {{ switched_on_entities_names | join(', ') }}.
            default:
              - service: "notify.{{ group_target }}"
                data:
                  title: "Amber Price Alert Notification"
                  message: >
                    The price of ${{ states(price_entity) }} has exceeded {{ '$%.2f'| format(price_threshold | float | multiply(0.01)) }}. Turning off the following entities: {{ switched_on_entities_names | join(', ') }}.

#          - service: homeassistant.turn_off
#            target:
#              entity_id: >
#                {{ switched_on_entities | join(', ') }}
