blueprint:
  name: Price Alert with Entity Status Notification
  description: Sends a Pushbullet notification if the price tracking entity goes above a predefined value and any specified entities are switched on.
  domain: automation
  input:
    price_entity:
      name: Price Tracking Entity
      description: The entity that tracks the price.
      selector:
        entity:
          domain: sensor
    price_threshold:
      name: Price Threshold
      description: The price value that triggers the alert.
      selector:
        number:
          min: 0
          max: 100
    notify_device:
      name: Pushbullet Device
      description: The Pushbullet device to send notifications to.
      selector:
        device:
          integration: pushbullet
    monitored_entities:
      name: Monitored Entities
      description: List of entities to monitor.
      selector:
        entity:
          domain: switch
          multiple: true

variables:
  price_entity: !input price_entity
  price_threshold: !input price_threshold
  notify_device: !input notify_device
  monitored_entities: !input monitored_entities

trigger:
  - platform: numeric_state
    entity_id: !input price_entity
    above: !input price_threshold

condition: []

action:
  - variables:
      switched_on_entities: >
        {{ expand(variables.monitored_entities) | selectattr('state', 'eq', 'on') | map(attribute='entity_id') | list }}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ switched_on_entities | length > 0 }}"
        sequence:
          - service: notify.pushbullet
            data:
              target: !input notify_device
              message: >
                The price of {{ states(price_entity) }} has exceeded {{ price_threshold }}. The following entities are switched on: {{ switched_on_entities | join(', ') }}.
              title: Price Alert Notification
